on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Hello world action step
        id: hello
      # Runs a set of commands using the runners shell
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: 'Vinicius'
        
        #output
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time}}"
